"""TensorEval core module — types, errors, decorators, sample, score."""

from tensoreval.core.errors import (
    Error,
    EvaluationError,
    InfraError,
    ModelError,
    SandboxError,
    ToolError,
    TrainingError,
)
from tensoreval.core.sample import Sample
from tensoreval.core.score import Score, RubricScore, Value, CORRECT, INCORRECT, PARTIAL, NOANSWER
from tensoreval.core.types import (
    AssistantMessage,
    CustomBaseModel,
    GenerateOutputs,
    GenerateMetadata,
    Message,
    Messages,
    Response,
    RolloutInput,
    RolloutOutput,
    RolloutScore,
    RolloutTiming,
    SamplingArgs,
    State,
    SystemMessage,
    TimeSpan,
    Tool,
    ToolCall,
    ToolMessage,
    TrajectoryStep,
    Usage,
    UserMessage,
    flatten_task_input,
    state_to_output,
)
from tensoreval.core.decorators import (
    advantage,
    cleanup,
    discover_decorated,
    metric,
    reward,
    setup,
    stop,
    teardown,
)

__all__ = [
    # Errors
    "Error",
    "EvaluationError",
    "InfraError",
    "ModelError",
    "SandboxError",
    "ToolError",
    "TrainingError",
    # Data models
    "Sample",
    "Score",
    "RubricScore",
    "Value",
    "CORRECT",
    "INCORRECT",
    "PARTIAL",
    "NOANSWER",
    # Types
    "AssistantMessage",
    "CustomBaseModel",
    "GenerateOutputs",
    "GenerateMetadata",
    "Message",
    "Messages",
    "Response",
    "RolloutInput",
    "RolloutOutput",
    "RolloutScore",
    "RolloutTiming",
    "SamplingArgs",
    "State",
    "SystemMessage",
    "TimeSpan",
    "Tool",
    "ToolCall",
    "ToolMessage",
    "TrajectoryStep",
    "Usage",
    "UserMessage",
    "flatten_task_input",
    "state_to_output",
    # Decorators
    "advantage",
    "cleanup",
    "discover_decorated",
    "metric",
    "reward",
    "setup",
    "stop",
    "teardown",
]
