"""Score data model for TensorEval evaluation results.

Adapted from Inspect AI (MIT License, UK AISI).
"""

from typing import Any, Mapping, Sequence, Union

from pydantic import BaseModel, Field


# Score value constants
CORRECT = "C"
INCORRECT = "I"
PARTIAL = "P"
NOANSWER = "N"

Value = Union[
    str | int | float | bool,
    Sequence[str | int | float | bool],
    Mapping[str, str | int | float | bool | None],
]
"""Value provided by a score."""


class Score(BaseModel):
    """Score generated by a scorer/grader."""

    value: Value
    """Score value — can be scalar, sequence, or mapping."""

    answer: str | None = Field(default=None)
    """Answer extracted from model output (optional)."""

    explanation: str | None = Field(default=None)
    """Explanation of score (optional)."""

    metadata: dict[str, Any] | None = Field(default=None)
    """Additional metadata related to the score."""

    @property
    def text(self) -> str:
        """Read the score as text."""
        return self.as_str()

    def as_str(self) -> str:
        """Read the score as a string."""
        return str(self._as_scalar())

    def as_int(self) -> int:
        """Read the score as an integer."""
        return int(self._as_scalar())

    def as_float(self) -> float:
        """Read the score as a float."""
        return float(self._as_scalar())

    def as_bool(self) -> bool:
        """Read the score as a boolean."""
        return bool(self._as_scalar())

    def _as_scalar(self) -> Any:
        if isinstance(self.value, (str, int, float, bool)):
            return self.value
        if isinstance(self.value, Sequence):
            return self.value[0] if self.value else 0
        if isinstance(self.value, Mapping):
            vals = [v for v in self.value.values() if v is not None]
            return vals[0] if vals else 0
        return self.value


class RubricScore(BaseModel):
    """Score for a single rubric within a query evaluation."""

    rubric_name: str
    """Name of the rubric."""

    score: float = Field(ge=0.0, le=1.0)
    """Score between 0.0 and 1.0."""

    weight: float = Field(ge=0.0, le=1.0)
    """Weight of this rubric (sums to 1.0 across all rubrics for a query)."""

    reasoning: str = ""
    """Reasoning for this score."""
